[package]

name = "itevenworks"
version = "0.0.1"
authors = ["Raul Gutierrez S. <rgs@itevenworks.net>"]

[dependencies]
nickel = "*"
nickel_macros = "*"
getopts = "*"
regex = "*"
rustc-serialize = "*"
